const PASSWORD_FIELD = 'password';
const DATE_TIME_FORMAT = 'DD-MM-YYYY_HH-mm-ss';
const TRANSACTION_STATUS = {
  PENDING: 'pending',
};

export { PASSWORD_FIELD, DATE_TIME_FORMAT, TRANSACTION_STATUS };
